name: "davidkhala/uv-buildpack"
description: A typical uv build steps. Assume you have checkout source already

branding:
  icon: 'package'
  color: 'yellow'
inputs:
  tests:
    description: 'Test Sources Root: working-directory of your tests'
    required: false
    default: tests
  test-entry-point:
    description: 'script of test command'
    required: false
  version:
    description: 'python version'
    required: false
  working-directory:
    description: 'poetry home path'
    required: false
    default: .
  extras:
    description: 'extras to be installed'
    required: false
runs:
  using: "composite"
  steps:
  - if: ${{ inputs.version != '' }}
    uses: actions/setup-python@main
    with:
      python-version: ${{ inputs.version == 'latest' && '3.x' || inputs.version }}
  - uses: astral-sh/setup-uv@main
    with:
      version: "latest"

  - name: Sync dependencies
    shell: bash
    working-directory: ${{inputs.working-directory}}
    run: |
      EXTRA_ARGS=""
      for extra in ${{ inputs.extras }}; do
        EXTRA_ARGS="$EXTRA_ARGS --extra $extra"
      done
      if [ -z "${{ inputs.extras }}" ]; then
        uv sync --all-extras
      else
        uv sync $EXTRA_ARGS
      fi  

  - if: ${{ inputs.test-entry-point != '' }}
    run: uv run ${{ inputs.test-entry-point }}
    working-directory: ${{ inputs.tests }}
    shell: bash
